### PR TITLE
Added post installation pages for apps.

### LINKED ISSUE #4: Post installation page for apps
A lot of apps have steps that need to be taken after installation. For example, the [stale](https://github.com/probot/stale#usage) plugin requires a `.config/stale.yml`, and the [DCO](https://github.com/probot/dco) plugin optionally suggests [required statuses](https://github.com/probot/dco/blob/master/docs/required-statuses.md).

It might be nice if all of the listed apps had a post-install page (e.g. `https://probot.github.io/apps/stale/install`) with info on what to do after installing the app.

### PR DESCRIPTION
**Pull request by knrt10**
Closes #4 .

**Preview**

### CODE REVIEW

**Comment by hiimbex** [comment]
HI @knrt10 thanks for the PR! I was wondering if there was any difference between the listings in `_install` versus the original listings from `_apps`. I think the original goal from the issue was to support apps that had specific post-install steps or configurations necessary. So I'm not quite sure every app needs one.

Ideally, this could be an opt in system. I'm not sure there even needs to be a button on the website, I think folks would link to it from the post install version of the GitHub App itself ie this field:

screen shot 2018-04-14 at 11 13 15 am

**Comment by knrt10** [comment]
@hiimbex you are totally right but as issue suggested
>It might be nice if all of the listed apps had a post-install page (e.g. https://probot.github.io/apps/stale/install) with info on what to do after installing the app.

The task was make post install pages for apps which needed any. And many of them didn't needed that so I made some default for apps which didn't have them. Like how user's can deploy that application.

Now as you say 
>Ideally, this could be an opt in system. I'm not sure there even needs to be a button on the website, I think folks would link to it from the post install version of the GitHub App itself ie this field:

That is totally correct but we want to to help users from probot's site only what they can/have to do after install. It's like reducing task for people who posted apps on our site.

Ideal situation as per me would be asking users who post their apps on our site to add another extension in their template like

```
# Post install page
postInstallpage: yes

screenshotPostInstall: // something
```

. If they put yes in postInstallpage we will show the button(info after install) and also the screenshot they posted and if they don't we won't show it.

**Comment by knrt10** [comment]
@hiimbex any thoughts on this?

**Comment by bkeepers** [comment]
I don't think this is quite the approach we want to take. Thanks @knrt10 for taking the time to try to resolve this issue though.

**Pull request closed without merging**
