### PR TITLE
Polish app cards

### PR DESCRIPTION
**Pull request by j-f1**
This PR also fixes a typo in the `{% octicon %}` tags.

screen shot 2017-10-27 at 15 34 12

### CODE REVIEW

**Comment by JasonEtco** [comment]
Hey @j-f1! Can you please elaborate on what this PR changes, aside from the typo in the `{% octicon %}` tags? I pulled down your branch and compared it the live site and didn't see any difference in the app cards. Thanks 💖

**Comment by j-f1** [comment]
@JasonEtco 

> Can you please elaborate on what this PR changes

Before:
before

After:
after

**Comment by JasonEtco** [comment]
@j-f1 thanks for the screenshots, sorry about the delay on my part. I've looked for the **Before** bug in Chrome, Edge, Safari and Firefox (the new beta version) and I haven't seen it. What browser did you catch this in?

**Comment by j-f1** [comment]
> I've looked for the Before bug in Chrome, Edge, Safari and Firefox (the new beta version) and I haven't seen it.

I saw the boxes being different heights on Safari. It might be that it’s been fixed in Primer, or that Safari is rendering the content incorrectly. I can see the sharp corners bug on Safari and Chrome.

**Comment by JasonEtco** [comment]
@j-f1 I've seen bugs like that in Safari, I'm curious why I'm not seeing it now. I'll do some more digging 👍

**Comment by JasonEtco** [comment]
Some more digging later, I still don't see where this occurs, but I'm going to merge it anyway since it seems to happening for more people than me, and these changes to really harm anything. Thanks @j-f1, and sorry about the delay!

**Pull request merged**
