### PR TITLE
Favicon addition

### PR DESCRIPTION
**Pull request by Jme7**
- Favicon addition
- used imgbot and resyled.io (github apps)

Also, try to add this code to the head of your webpages:
```
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

```

### CODE REVIEW

**Comment by Jme7** [comment]
@gr2m here is the pull request

**Comment by gr2m** [comment]
What is browserconfig.xml? And why did you delete a ton of files in this pull request? It seems to be unrelated to adding the favicon?

**Comment by Jme7** [comment]
Did I delete files? sorry I am going to close this. I was using a favicon generator,  so sorry about all of this if it is wrong.

**Comment by gr2m** [comment]
No worries, feel free to try again

**Comment by Jme7** [comment]
What exactly was deleted?

**Comment by gr2m** [comment]
You can see all changes in the "files" tab of the pull request. Here are all changed files for this pull request:
https://github.com/probot/probot.github.io/pull/341/files

**Comment by Jme7** [comment]
Huh, it looks like alot of deleting nothing and adding nothing. That probably was from resyled.io or imgbot.
I will try again without using them

**Comment by Jme7** [comment]
Could I have the image for probot's favicon? I could take a screenshot, but that leaves a white box where there should be trasparancy.

**Comment by gr2m** [comment]
The logo is here, does that work for you?
https://github.com/probot/probot.github.io/blob/master/assets/logo.png

**Comment by Jme7** [comment]
Kind of, but I need the head, because the head was the favicon

**Comment by gr2m** [comment]
I found the an SVG for the logo and an PNG for just the head:
https://github.com/probot/probot/tree/master/static

**Comment by Jme7** [comment]
Thanks! I will start working on this

**Pull request closed without merging**
