### PR TITLE
Add Repost Probot App to _apps

### PR DESCRIPTION
**Pull request by philip-gai**
##### Checklist

- [x] If you're adding a listing for your app, be sure your app is in the `/_apps/` folder before opening this Pull Request.
- [x] All comments in frontmatter need to be removed.
- [x] Performs a useful action through the GitHub API that solves an existing problem for developers: Teammates can gather feedback on discussion posts via PRs and no longer have to copy/paste markdown or get feedback use Google Docs or something outside of GitHub.
- [x] Is original: for example, it does something not already done by an existing Probot app
- [x] [Has tests](https://github.com/philip-gai/repost-demo) - Still somewhat manual right now but I've been doing testing in this demo repo 😞 
- [x] [Has documentation](https://github.com/philip-gai/repost)
- [x] [Is open source](https://github.com/philip-gai/repost/blob/main/LICENSE)
- [x] [Has a license](https://github.com/philip-gai/repost/blob/main/LICENSE)
- [x] [Has a code of conduct](https://github.com/philip-gai/repost/blob/main/CODE_OF_CONDUCT.md)
- [x] Has someone willing to at least minimally maintain them for the near future: @philip-gai

-----
[View rendered _apps/repost.md](https://github.com/philip-gai/probot.github.io/blob/patch-1/_apps/repost.md)

### CODE REVIEW

**Comment by gr2m** [comment]
This looks great!

Two things

1. Out of curiosity, what is the use case for your app? Why not ask people to just open discussions?
2. I would recommend you rename the app slug from https://github.com/apps/repo-st to https://github.com/apps/repost before promoting the app. It might not be permitted because there is an org with the same name: https://github.com/repost. But that org seems to be dormant for 10 years, might be worth to ask GitHub to help you get in touch with the owners of the app, maybe they are willing to remove the org

**Comment by philip-gai** [comment]
@gr2m thanks for the feedback!

> 1. Out of curiosity, what is the use case for your app? Why not ask people to just open discussions?

This is mainly for things like announcements or organization team posts that you want your teammates feedback on before posting. At github, we have a ton of team posts that notify hundreds of people. Most author's want that team post to be proofread and reviewed before posting it, so a lot of team repos have a `docs/team_posts` folder where they stored the post and maybe asked for feedback. Others write the post in Google Docs, get it reviewed, then rewrite it in markdown, add gifs, emojis etc and then post. Once they got the feedback they then copy/pasted the post to actually publish it to the larger team / org.

If you use this app, you can use your small team repo to get the feedback and once you merge the PR it will post it for you to ANY repo or team that you specify and the app is authorized for. You can also use a private, internal team repo to draft things like big product announcements, get them reviewed, and merge once you're ready for it to be posted and it can create the post in your public repo. And you get the added benefit of PR checks, policies etc.

> 2. I would recommend you rename the app slug from https://github.com/apps/repo-st to https://github.com/apps/repost before promoting the app.

Yeah that makes sense. It's because I named it `(repo)st` so the slug became `repo-st`. It's supposed to be a play on repo + post that you can see visually but it's not super important. I will see if I can get the org removed, if not I might just go for `repost-app` or something like that

**Review by gr2m — APPROVED** [review]
Thanks for the explanation, I can totally see the advantage of drafting an announcement app together. Maybe you should call it `announcement-drafter` instead, at least for me that'd have made its core benefit obvious right away :) 

If you rename the app in future just send another PR

**Comment by philip-gai** [comment]
I think that's a great idea, I probably will rename it. Thanks! 😊👍🏼

**Pull request merged**
