### PR TITLE
Fix cutoff code on homepage

### LINKED ISSUE #200: Code section on website not properly overflowing
Due to the changes from https://github.com/probot/probot.github.io/pull/199, The website code sections looks wonky with the code getting cut off:

screen shot 2018-06-28 at 6 11 29 pm

I'm guessing the fix is a simple change to this div:
https://github.com/probot/probot.github.io/blob/ea3ab5fbaa6a705a4dfca2158fc3d9f053ff5bdf/index.html#L82-L93

### PR DESCRIPTION
**Pull request by JasonEtco**
Fixes the cutoff code on the homepage by tweakin' some column classes.

image

Closes #200

### CODE REVIEW

**Comment by JasonEtco** [comment]
@hiimbex CI is failing :sob:

**Comment by hiimbex** [comment]
The failures are due to https://github.com/probot/probot/pull/604
But not sure why https://github.com/tcbyrd is failing, although I do get a 500 visiting it myself 😬 any ideas why that is @tcbyrd lol

I think you can go ahead and merge since the failures are totally unrelated

**Comment by tcbyrd** [comment]
> But not sure why https://github.com/tcbyrd is failing, although I do get a 500 visiting it myself

I think this is a bug due to a feature flag on my account. I reported it internally. Don't worry about it here.

**Comment by hiimbex** [comment]
Then I would go ahead and 🚢 when ready @JasonEtco

**Pull request merged**
