### PR TITLE
Add branch-switcher

### PR DESCRIPTION
**Pull request by s4heid**
##### Checklist

- [x] If you're adding a listing for your app, be sure your app is in the `/_apps/` folder before opening this Pull Request.
- [x] All comments in frontmatter need to be removed.
- [x] Performs a useful action through the GitHub API that solves an existing problem for developers: when a pull request has been opened against a wrong branch, branch-switcher changes the base to the preferred branch.
- [x] Is original: for example, it does something not already done by an existing Probot app
- [x] [Has tests](https://github.com/s4heid/branch-switcher/tree/master/test)
- [x] [Has documentation](https://github.com/s4heid/branch-switcher/blob/master/README.md)
- [x] [Is open source](https://github.com/s4heid/branch-switcher)
- [x] [Has a license](https://github.com/s4heid/branch-switcher/blob/master/LICENSE)
- [x] [Has a code of conduct](https://github.com/s4heid/branch-switcher/blob/master/CODE_OF_CONDUCT.md)
- [x] Has someone willing to at least minimally maintain them for the near future: [s4heid](https://github.com/s4heid)

-----
[View rendered _apps/branch-switcher.md](https://github.com/s4heid/probot.github.io/blob/branch-switcher/_apps/branch-switcher.md)

### CODE REVIEW

**Comment by s4heid** [comment]
Hey @JasonEtco, thanks for your feedback. I just pushed a fix and the `/ping` endpoint returns a response now:
```
$ curl https://branch-switcher.now.sh/ping
PONG
```

I'm not sure how to trigger the ci tests again, though.

**Comment by gr2m** [comment]
I've restarted the build

**Comment by gr2m** [comment]
The error is unrelated, let's merge :)

**Comment by s4heid** [comment]
Thank you @gr2m :)

**Pull request merged**
