### PR TITLE
feat: added Semantic PR Title app file

### PR DESCRIPTION
**Pull request by coleHafner**
##### Checklist

- [x] If you're adding a listing for your app, be sure your app is in the `/_apps/` folder before opening this Pull Request.

- [ ] All comments in frontmatter need to be removed.
> frontmatter? 

- [x] Performs a useful action through the GitHub API that solves an existing problem for developers: {explain the action here}

- [x] Is original: for example, it does something not already done by an existing Probot app
> There's [another app](https://github.com/probot/probot.github.io/blob/master/_apps/semantic-pull-requests.md) that does something similar, but I could not get it to work for my org/private repo. Mine works differently, as it only focuses on the PR title and uses a regex instead of commit lint. It's more flexible in that way since it could be used for anything that can be validated with a regex. 

- [x] [Has tests](https://github.com/coleHafner/semantic-pr-title/blob/master/test/index.test.js)
- [x] [Has documentation](https://github.com/coleHafner/semantic-pr-title#config)
- [x] [Is open source](https://github.com/coleHafner/semantic-pr-title)
- [x] [Has a license](https://github.com/coleHafner/semantic-pr-title/blob/master/LICENSE)
- [x] [Has a code of conduct](https://github.com/coleHafner/semantic-pr-title/blob/master/CODE_OF_CONDUCT.md)
- [x] Has someone willing to at least minimally maintain them for the near future: [coleHafner](https://github.com/coleHafner)

-----
[View rendered _apps/semantic-pr-title.md](https://github.com/coleHafner/probot.github.io/blob/patch-1/_apps/semantic-pr-title.md)

### CODE REVIEW

**Comment by gr2m** [comment]
> There's [another app](https://github.com/probot/probot.github.io/blob/master/_apps/semantic-pull-requests.md) that does something similar, but I could not get it to work for my org/private repo. Mine works differently, as it only focuses on the PR title and uses a regex instead of commit lint. It's more flexible in that way since it could be used for anything that can be validated with a regex.

It sounds like it would be better to collaborate with the authors on the other app? @zeke is the other app yours?

**Comment by coleHafner** [comment]
@gr2m I did [file an issue](https://github.com/probot/semantic-pull-requests/issues/70), but haven't got much traction so far.

**Comment by zeke** [comment]
I agree that this app is very similar to the existing https://github.com/probot/semantic-pull-requests app. Based on the conversation in https://github.com/probot/semantic-pull-requests/issues/70, it appears that the desired functionality is not working on private repos, though it works on public repos. It seems like it might be a scope/permissions issue with the app. I don't have time to prioritize fixing that issue, but I will happily review, merge, and deploy a pull request that solves the problem.

**Comment by cyberhck** [comment]
actually I'd consider the usecase you've added as a duplicate of semantic-pull-requests, can you add a config where there's something else,? because semantic-pull-request app already exists :)

**Comment by coleHafner** [comment]
Go ahead and close it.

**Pull request closed without merging**
