### PR TITLE
Installations

### PR DESCRIPTION
**Pull request by bkeepers**
Now that https://github.com/probot/probot/pull/181 landed in probot, this updates the website to sync the public stats and show number of installations and popular organizations.

probot___github_apps_to_automate_and_improve_your_workflow

---

stale___probot

---

Before this can get merged, I need to know the URL that the following apps are deployed to so we can fetch the `/probot/stats`. If you're tagged here, can you just comment with the URL for your app? (You'll need to make sure you're running on the latest probot, which you can test by fetching the [`/probot/stats`](http://probot-stale.herokuapp.com/probot/stats) endpoint)

- [ ] gpg (@jarrodldavis)
- [x] invite-contributors (@erickzhao)
- [x] todo (@JasonEtco)
- [x] validate-commit-msg-bot (@tlvince)
- [x] wip (@gr2m)

Also, the following apps need to update to the latest probot with `npm install probot@latest`:

- [x] first-timers (@agonzalez0515, @Techforchange)
- [x] sentiment-bot (@hiimbex)
- [x] update-docs (@hiimbex)
- [x] welcome (@hiimbex)
- [x] wip (@gr2m)

### CODE REVIEW

**Comment by JasonEtco** [comment]
Until further notice, mines running at `https://todo-api.jasonet.co`, and [the stats page](https://todo-api.jasonet.co/probot/stats) works fine.

**Comment by JasonEtco** [comment]
@bkeepers, First timers is running here: `https://first-timers-bot.now.sh/probot/stats`, shouldn't need any newer versions

**Comment by hiimbex** [comment]
Nice! Style-wise Do you think it would make sense to list the used by section in the gray area above, under Updated? That's where it originally lived and I kinda liked it there

**Comment by bkeepers** [comment]
> Nice! Style-wise Do you think it would make sense to list the used by section in the gray area above, under Updated? That's where it originally lived and I kinda liked it there

I had tried that and ran into some problems with dark avatars with transparent backgrounds. Setting a white background on the avatars seems to help:

stale___probot

**Comment by bkeepers** [comment]
Oops, wrong screenshot, here you go:

stale___probot

**Comment by hiimbex** [comment]
I worry what it will look like for app's with very short descriptions. Take for example WIP: https://probot.github.io/apps/wip/ because the description is so short, the lack of content there might feel awkward.

**Comment by JasonEtco** [comment]
I'm +1 for keeping it on white; its more consistent with GitHub's usage of avatars, which means its less likely that an avatar will look wonky since it'd be resolved already (if the project owners cared to do so).

@hiimbex, you make a good point about the small text. I'm ok with that compromise, but I would also suggest that apps try to have a little more to their description. Using WIP as an example, I think it should have a screenshot or two and a more verbose explanation. That may not be possible for all apps, but I think its ok to have the popular installations be larger than the text in those cases.

**Comment by hiimbex** [comment]
>  Using WIP as an example, I think it should have a screenshot or two and a more verbose explanation. 

I'm actually fine with the WIP text. I think it's a pretty self explanatory app, and the gif basically shows all possible behaviors.

re: design stuff, I'm +1 for moving it up and having white backgrounds.

**Comment by JasonEtco** [comment]
Ah thats true, I forgot about the GIF.

I'm fine with either one, godspeed team 👍

**Comment by erickzhao** [comment]
Hey @bkeepers! `invite-contributors` is running at `https://vast-stream-78160.herokuapp.com` and the [stats page](https://vast-stream-78160.herokuapp.com/probot/stats) works.

**Comment by hiimbex** [comment]
all behaviorbot apps updated to latest probot and confirmed all stats pages work.
Links: http://probot-welcome.herokuapp.com/probot/stats
http://probot-sentiment-bot.herokuapp.com/probot/stats
http://probot-request-info.herokuapp.com/probot/stats
http://probot-update-docs.herokuapp.com/probot/stats

**Comment by tlvince** [comment]
validate-commit-msg-bot updated: https://validate-commit-msg-bot-qehbpuliwa.now.sh/probot/stats

**Comment by gr2m** [comment]
wip: https://wip-bot.now.sh/probot

**Comment by jarrodldavis** [comment]
I've just updated my deployment of `gpg` and the stats are available at http://probot-gpg-production.herokuapp.com/probot/stats.

**Pull request merged**
