### PR TITLE
Create pr-label-enforcer.md

### PR DESCRIPTION
**Pull request by cyberhck**
##### Checklist

- [x] If you're adding a listing for your app, be sure your app is in the `/_apps/` folder before opening this Pull Request.
- [ ] All comments in frontmatter need to be removed. (Don't know what this is)
- [x] Performs a useful action through the GitHub API that solves an existing problem for developers: {it adds status checks before a branch is merged, it uses labels which can be configured}
- [x] Is original: for example, it does something not already done by an existing Probot app
- [x] [Has tests](https://github.com/fossapps/pr_label_enforcer)
- [x] [Has documentation](https://github.com/fossapps/pr_label_enforcer) since it's a typescript app, I'd say code is documentation
- [x] [Is open source](https://github.com/fossapps/pr_label_enforcer) (Of course, everything I do except my full time job is opensource)
- [x] [Has a license](https://github.com/fossapps/pr_label_enforcer/blob/master/LICENSE.md)
- [x] [Has a code of conduct](https://github.com/fossapps/pr_label_enforcer/blob/master/CODE_OF_CONDUCT.md)
- [x] Has someone willing to at least minimally maintain them for the near future: {Nishchal Gautam @cyberhck }

closes probot/ideas#93

-----
[View rendered _apps/pr-label-enforcer.md](https://github.com/cyberhck/probot.github.io/blob/patch-1/_apps/pr-label-enforcer.md)

### CODE REVIEW

**Comment by cyberhck** [comment]
By default it doesn't do anything, a yaml file is used to configure, https://github.com/marketplace/pr-label-enforcer please check that for info, hmm, looks like I forgot to include that info on app page, repository, and on this markdown, will update gimme some time

**Comment by cyberhck** [comment]
basically, it's just this: https://github.com/probot/ideas/issues/93

**Comment by cyberhck** [comment]
@gr2m did you have a chance to look into this one?

**Comment by gr2m** [comment]
Sorry for the delay and the lack of transparancy. We are currently discussing what do with the app gallery, we might remove it entirely.

One thing you can do is to submit the app to the marketplace, it's now possible to have it listed as an "unverified" app. 

If we keep the app gallery, then we will likely require the app to be listed in the marketplace first

**Comment by cyberhck** [comment]
it's already listed to marketplace :)

**Comment by cyberhck** [comment]
the main reason I wanted to add unpublished app to app gallery is because I could get some users who would install the app (if you want to publish your app to marketplace, you need to have at least 10 users)

IMO, removing app gallery OR requiring it to be published to marketplace seems like a wrong move. Is that purely because you don't want to maintain this repo?

This project served as a secondary marketplace to show that a project is useful so people would install it and get marketplace registered.

**Comment by gr2m** [comment]
Good point, thanks. There are other ways we can help promote an app. I'll get back to you once we discussed how we want to move forward

**Comment by cyberhck** [comment]
@gr2m how about we merge this?

**Comment by gr2m** [comment]
Can you add a description?

**Comment by cyberhck** [comment]
description where? You mean on my app? or here on PR?

**Comment by gr2m** [comment]
To `_apps/pr-label-enforcer.md`, it currently only containts frontmatter, compare to the other files in `_apps/*`

**Comment by cyberhck** [comment]
hello, thanks, it's done :)

**Comment by gr2m** [comment]
Thanks :)

**Pull request merged**
