### PR TITLE
Add Similar Code Searcher to apps

### PR DESCRIPTION
**Pull request by Ikuyadeu**
Added my prototype bot for GSoC on https://github.com/probot/ideas/issues/50.
Let me know what you think  :smile:

### CODE REVIEW

**Comment by hiimbex** [comment]
Hi @Ikuyadeu thanks for the PR! I'm glad you took the time to develop it and I'm sorry we didn't get back to you sooner! 

I will say though, I'm a bit confused about how this bot actually works and the problem it's attempting to solve for developers. Do you think you could provide me with an in depth use case? Otherwise I'll be closing this out.

**Comment by Ikuyadeu** [comment]
Hi @hiimbex thank you for the review and sorry for lack of explanation.
They are my opinion for this bot.

* Problem:  Developers sometimes forget to change files or components that should be changed at the same time.
* Solution:  Propose files that should be changed simultaneously by searching for similar lines.

* How to Use:
  1. The developer submits a pull request
  2. Similar-code-searcher(bot) suggests similar source code files
  3. The developer and reviewers verify that should be change at the same time.
  4. Change similar code or ignore suggestion and merge PR

**Comment by hiimbex** [comment]
I see! Thanks for the explanation. I'd feel much more comfortable adding your app if you could add some of that explanation within the description, as well as explaining more thoroughly how it works, so that users know what to expect.

**Comment by Ikuyadeu** [comment]
@hiimbex could you see this changes?
If you have some idea for improvement, please request me.

**Pull request merged**
