### PR TITLE
Add contribute page

### PR DESCRIPTION
**Pull request by bkeepers**
This updates the contribute link at the top to link to a separate page. If office hours is within 4 hours, it also adds a nag banner to every page on the site, and a "Join Now" link.

I spent way to to much time trying to figure out what all should go on this page, and then just ended up deleting all of it.

@JasonEtco or anyone else that wants to fiddle with this page, if you have strong feels about this page, feel free to mess around with this PR.

### CODE REVIEW

**Comment by JasonEtco** [comment]
I love it, the Zoom screenshot is so cute! The line of 3 buttons is a little too airy I think; removing that extra space would probably be good. 

Also for consistency, we should either get a Twitter icon or remove the icons from the other two buttons.

I can make those changes in this PR if you'd like, not sure how you feel about others committing to your PR 👍

**Comment by bkeepers** [comment]
@jasonetco feel free to push to this branch. I agree with your suggestions.

**Comment by JasonEtco** [comment]
Looks like this as of my last two commits: 
image

**Comment by bkeepers** [comment]
Beautiful. :shipit:? Let me know when you’re happy with it and I’ll ege because of #14

**Comment by JasonEtco** [comment]
Fine with me @bkeepers , merge away 🚢 :shipit: 🐟

**Pull request merged**
