### PR TITLE
fix: change commitlint & DEP deployment URLs

### PR DESCRIPTION
**Pull request by ahmed-taj**
This PR changes the deployment URLs for both [commitlint](https://probot.github.io/apps/commitlint/) and [DEP](https://probot.github.io/apps/dep/) apps.

Related to #167 and #168

### CODE REVIEW

**Comment by ahmed-taj** [comment]
@bkeepers looks like Travis is failing for something unrelated to `commitlint` or `Dep`

**Comment by hiimbex** [comment]
travis seems to be failing due to CNXTEoEorg not being a public (?) organization that's listed as a org that uses the settings app: https://github.com/probot/probot.github.io/blob/master/_apps/settings.md

This makes sense given: https://github.com/CNXTEoEorg bounces. Not totally sure how to solve this

**Comment by j-f1** [comment]
Could be that it has been deleted?

**Comment by hiimbex** [comment]
@j-f1 that crossed my mind but I just hit the [stats endpoint](https://github-configurer.herokuapp.com/probot/stats) and it's still on there.

```
{"login":"CNXTEoEorg","id":1623538,"avatar_url":"https://avatars1.githubusercontent.com/u/1623538?v=4","gravatar_id":"","url":"https://api.github.com/users/CNXTEoEorg","html_url":"https://github.com/CNXTEoEorg","followers_url":"https://api.github.com/users/CNXTEoEorg/followers","following_url":"https://api.github.com/users/CNXTEoEorg/following{/other_user}","gists_url":"https://api.github.com/users/CNXTEoEorg/gists{/gist_id}","starred_url":"https://api.github.com/users/CNXTEoEorg/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/CNXTEoEorg/subscriptions","organizations_url":"https://api.github.com/users/CNXTEoEorg/orgs","repos_url":"https://api.github.com/users/CNXTEoEorg/repos","events_url":"https://api.github.com/users/CNXTEoEorg/events{/privacy}","received_events_url":"https://api.github.com/users/CNXTEoEorg/received_events","type":"User","site_admin":false,"stars":28581},
```

And I feel like they wouldn't be in the github api any more if they were truly deleted. But also it's a user not an org, and I don't think users can be private, so maybe that is the case!

**Comment by hiimbex** [comment]
@bkeepers any thoughts about this? I think this failure is bizarre but unrelated to this PR

**Comment by bkeepers** [comment]
This is an issue with users being marked as spammy. Unfortunately the API still returns these accounts and doesn't report on their spammy-ness since it would allow spammers to easily detect what actions trigger spam detection.

https://github.com/probot/scheduler/pull/17 was added to skip accounts like this for scheduler. We should update the stats endpoint to support the same env var.

**Comment by j-f1** [comment]
Would it be possible to fetch `https://github.com/username`, and only include the user if it doesn’t 404?

**Pull request merged**
