### PR TITLE
Delete lock app due to 502 status

### PR DESCRIPTION
**Pull request by gr2m**
ping @dessant. The current URL responds with 502 which causes our CI to fail:
https://lock-threads.apps.armin.dev/ping

### CODE REVIEW

**Comment by dessant** [comment]
Sorry for the CI fail, I have restarted the service. Some users are adding all their repositories and the container runs out of memory, I'll have to prune the abusive accounts.

**Comment by gr2m** [comment]
Got it, good luck with that!

**Comment by gr2m** [comment]
@dessant looks like the problem occurred again, can you check?

**Comment by dessant** [comment]
Thanks for the ping, the service is up now. Is `/ping` the only endpoint that can cause a build failure on your part? I've added a rule in the server config to always respond with 200 "PONG" to not cause any more disruption. (please don't judge :yum:)

I plan to move away from using probot/scheduler for Lock Threads in the next few weeks as it doesn't scale well, and also release a GitHub Action as an alternative for locking threads.

**Comment by gr2m** [comment]
that all sounds good to me, thank you 👍

**Pull request closed without merging**
