### PR TITLE
Update design

### PR DESCRIPTION
**Pull request by AaronDewes**
A preview should be available at https://aarondewes.github.io/probot.github.io soon, not sure how long GitHub pages takes to make it available. This updates primer, introduces dark mode and makes some minor tweaks to the design

-----
[View rendered node_modules/@primer/css/CHANGELOG.md](https://github.com/AaronDewes/probot.github.io/blob/update-design/node_modules/@primer/css/CHANGELOG.md)
[View rendered node_modules/@primer/css/README.md](https://github.com/AaronDewes/probot.github.io/blob/update-design/node_modules/@primer/css/README.md)
[View rendered node_modules/@primer/css/alerts/README.md](https://github.com/AaronDewes/probot.github.io/blob/update-design/node_modules/@primer/css/alerts/README.md)
[View rendered node_modules/@primer/css/autocomplete/README.md](https://github.com/AaronDewes/probot.github.io/blob/update-design/node_modules/@primer/css/autocomplete/README.md)

### CODE REVIEW

**Comment by gr2m** [comment]
Thank you for all your contributions @AaronDewes. https://probot.github.io/ really needs some love! 

> A preview should be available at https://aarondewes.github.io/probot.github.io soon

I think the preview is there, but the assets are loaded with a `/` prefix, so they all result in 404 because they are tried to being loaded from https://aarondewes.github.io/ instead of https://aarondewes.github.io/probot.github.io, e.g https://aarondewes.github.io/assets/logo.png

Unfortunately I cannot manage to set up the jekyll locally, `bundle install` always fails for me. I'd love to get rid of jekyll altogether and use something else, so Probot contributors don't need to worry about yet another toolchain besides node. Do you have any preference yourself?

**Comment by AaronDewes** [comment]
> I'd love to get rid of jekyll altogether and use something else, so Probot contributors don't need to worry about yet another toolchain besides node. Do you have any preference yourself?

How about Gatsby? I can try to implement it if you want.

**Comment by gr2m** [comment]
Gatsby might be overkill? And I'm not very familiar with it, it looks rather complex and I'd be nervous that we wouldn't be able to maintain it when you move on to other projects. But if you think it's simple enough and you would like to give it a try to convince us, please feel free :)

As an alternative suggestion: are you familiar with https://www.11ty.dev/?

**Comment by AaronDewes** [comment]
Not really familiar with it, but I can try it the day after tomorrow if you want.

**Comment by gr2m** [comment]
Another option is next.js, which might be a bit more complicated, but it would permit us to easily add dynamically generated pages later

you choice! I'm a bit familiar with 11ty and next.js, these would be my preferences, but feel free to give Gatsby a go

**Comment by AaronDewes** [comment]
Next.js isn't optimized for GitHub pages though, it's better for vercel. But I have a bit of next experience, so I might try it. I'll create some concepts the day after tomorrow.

**Comment by gr2m** [comment]
okay lets do 11ty then, okay @AaronDewes? I'd be open to experiment with next.js in future if the need for dynamic page rendering comes up. We will of course need to change the domain then to something like probot.dev, but let's take one step at a time

**Comment by AaronDewes** [comment]
grafik
I made some progress on the 11ty site, but it's not finished yet.

**Comment by AaronDewes** [comment]
@gr2m This would require changes to the main probot repo because Jekyll and 11ty work slightly different and there are some issues with the docs. Would that be okay for you?

**Comment by AaronDewes** [comment]
Apps & docs not working, but https://probot-testsite.github.io/

**Comment by gr2m** [comment]
> @gr2m This would require changes to the main probot repo because Jekyll and 11ty work slightly different and there are some issues with the docs. Would that be okay for you?

yes, let me know what we need to change

**Comment by AaronDewes** [comment]
PR to the main repo is open, https://probot-testsite.github.io/ has been updated. After successfully merging this PR (#367), you need to change the github pages branch from master to gh-pages. But please note that after https://github.com/probot/probot/pull/1516, I still need to do some minor changes, updating the submodule & removing the docs folder from .eleventyignore.

**Comment by AaronDewes** [comment]
I still need to fix the docs, but it's nearly finished.

**Comment by AaronDewes** [comment]
Just force-pushed to make the review a bit easier: commit 99072ea8256de6e9091169b3b2e7ff1a0e3b4701 contains all the important changes, the other two only autogenerated, but big changes

**Comment by AaronDewes** [comment]
@gr2m It's getting late here, but probot-testsite seems to work now (except the things you said can be done in a follow-up PR), so you can merge this if you want, I'll do follow-up work tomorrow

**Comment by AaronDewes** [comment]
No, it's not working, all doc examples are one line right now

**Comment by AaronDewes** [comment]
@gr2m It should be ready now, can you have a look again?

**Review by gr2m — APPROVED** [review]
Code changes look good to me! Let's go 🚀

**Comment by gr2m** [comment]
New page is now deployed to and served from the `gh-pages` branch and live at https://probot.github.io/

If you like we could deploy to Netlify to get the previews on PRs?

**Pull request merged**
