### PR TITLE
Add Boomper app

### PR DESCRIPTION
**Pull request by toolmantim**
This adds [Boomper](https://github.com/toolmantim/boomper) to the list of apps 🎉

- [x] If you're adding a listing for your app, be sure your app is in the `/_apps/` folder before opening this Pull Request.
- [x] All comments in frontmatter need to be removed.

### CODE REVIEW

**Comment by toolmantim** [comment]
Taw, no `bot` — I emailed GitHub Support about this, and they said because there's a GitHub user called Boomper that it was reserved. I could rename the app slug to "Boomper App" or similar… just to get this to pass? 🤔

**Comment by hiimbex** [comment]
Awww, that sucks about the name, it's so cute too! The slug is critical to correctly linking to your app because it's: github.com/apps/your-slug to install the app, so it has to match. Boomper App could work, but feels repetitive; what about 'Boom-per'? (I know that's not great, but trying to brainstorm here) Even Boomper Bot sounds better, but @bkeepers might have strong feelings on this.

Out of interest you might wanna check our [greenkeeper](https://greenkeeper.io/), it's npm specific but has the same idea to bump version numbers; check it out [here](https://github.com/probot/probot/pull/593)!

**Comment by toolmantim** [comment]
Thanks for the review and ideas @hiimbex.

For background, I tried my best to avoid `Boomper Bot` as it definitely fails @bkeepers’s "bot" definition test — and I endorse the general vibes of that. I'd checked that https://github.com/apps/boomper wasn't available, but due to the "New Application" GH form error messages I wasn't aware of the username clash policy without emailing GH support, which took a while and I wanted to launch it. Booo!

Yep, Greenkeeper is awesome, but can't do what this app does I believe. I tend to use [Renovate](https://renovatebot.com) for dep updating (I actually use it already to keep these probot app deps up-to-date, [for example](https://github.com/toolmantim/boomper/pull/5)). This app was extracted from workflows maintaining [Buildkite Plugins](https://github.com/buildkite-plugins) — so people can keep their readmes auto-updated.

**Comment by hiimbex** [comment]
Sounds good @toolmantim! Feel free to update here once you've done so

**Pull request closed without merging**
