### PR TITLE
Add favicon files

### PR DESCRIPTION
**Pull request by Jme7**
@gr2m Here you go. I found out what browserconfig.xml, and site.webmanifest do. browserconfig is for websites pinned to start on windows 8 and 10, and webmanifest is for android chrome.
MAKE SURE TO ADD THIS TO HEAD OF WEBPAGES:
```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png?v=jw3d9vxKo4">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png?v=jw3d9vxKo4">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png?v=jw3d9vxKo4">
<link rel="manifest" href="/site.webmanifest?v=jw3d9vxKo4">
<link rel="mask-icon" href="/safari-pinned-tab.svg?v=jw3d9vxKo4" color="#5bbad5">
<link rel="shortcut icon" href="/favicon.ico?v=jw3d9vxKo4">
<meta name="msapplication-TileColor" content="#66cce0">
<meta name="theme-color" content="#66cce0">
```
After you add this (and GitHub Pages uploads the additions), you can check the favicon on different platforms here: https://realfavicongenerator.net/favicon_checker?protocol=https&site=probot.github.io%2F#.Xynad6-SkdV
(Also, you can go there now to see your current favicon setup)

### CODE REVIEW

**Comment by Jme7** [comment]
You can find the webpages of your website here: https://github.com/search?q=repo%3Aprobot%2Fprobot.github.io+language%3AHTML+language%3AHTML&type=Code (so that you can add the above code to them)

**Comment by gr2m** [comment]
The headers all go in this file: https://github.com/probot/probot.github.io/blob/master/_layouts/default.html

Would you like to add that to your pull request?

**Comment by Jme7** [comment]
Ok, I was wondering if you used a site-wide css file! I will!

**Comment by Jme7** [comment]
Done

**Comment by Jme7** [comment]
Is the Travis ci build anything to worry about?

**Comment by gr2m** [comment]
no I don't think so. It's about time we move away from Travis and use Actions instead. So if you are interested in helping that would be most appreciated

**Comment by Jme7** [comment]
I am glad to help! I don't know how much I CAN help though.... But if you need me, just @Jme7 me!

**Pull request merged**
