### PR TITLE
docs: change file extension to .md for all-contributors bot

### PR DESCRIPTION
**Pull request by jakebolam**
Per the spot on #280 (https://github.com/probot/probot.github.io/pull/280#issuecomment-456176376)

This may explain why the sync isn't working 😂(https://github.com/probot/probot.github.io/blob/master/script/sync-data#L10)

-----
[View rendered _apps/all-contributors.md](https://github.com/jakebolam/probot.github.io/blob/patch-1/_apps/all-contributors.md)

### CODE REVIEW

**Comment by jakebolam** [comment]
Builds failing:
```
  1) Failure:
lint test::_apps/all-contributors.md#test_0022_host returns 200 [test/lint_test.rb:59]:
Expected 200 response from https://gkioebvccg.execute-api.us-east-1.amazonaws.com/prod/ping.
Expected: "200"
  Actual: "403"
```

Do you need a ping endpoint?

**Comment by jakebolam** [comment]
Added a ping endpoint (https://github.com/all-contributors/all-contributors-bot/pull/95), re-triggered a build. Looks good now 👍 

Build failed on an un-related error
```
  1) Error:
lint test::_apps/profanity.md#test_0022_host returns 200:
Net::ReadTimeout: Net::ReadTimeout
```

**Comment by hiimbex** [comment]
I don't think it's super necessary, but it does help verify the website is up - for example, these linters fail a lot when apps go down or the appc reators change app names or domain names, and the first thing I check is the ping endpoint, so it's helpful to us. We would prefer to have it.

**Comment by jakebolam** [comment]
Thanks @hiimbex. Awesome! Working like a charm https://github.com/probot/probot.github.io/commit/b0d68b5d5ecea382f05cca9ee895bf4122505db5

**Pull request merged**
