### PR TITLE
fix layout

### PR DESCRIPTION
**Pull request by Arhell**
this PR fix issue https://github.com/probot/probot.github.io/issues/346

### CODE REVIEW

**Comment by Arhell** [comment]
@gr2m  review please

**Comment by gr2m** [comment]
It's not easy for me to review the change. I haven't contributed to the website code myself, and the local setup fails for me. Did you manage to test your change locally? If so, can you upload before/after screenshots in differen resolutions, or a short screenshare? That'd  be very helpful

**Comment by Arhell** [comment]
before in issue https://github.com/probot/probot.github.io/issues/346
after 



@gr2m  done
the block with the code goes beyond the boundaries of the container and its overflow properties do not work, but this fix fixes everything

**Comment by Arhell** [comment]
you can watch it online, just go to the site where there is a block with any code
for example https://probot.github.io/docs/hello-world/
and in the developer panel reduce the screen to 375 + -
you will see that it comes out, and apply the properties that I did in the PR and it will return to normal

**Comment by gr2m** [comment]
Got it, thank you!

**Pull request merged**
