### PR TITLE
Add ESLint Disable Watcher to apps

### PR DESCRIPTION
**Pull request by koddsson**
Added my own little Probot. Let me know what you think 😄

### CODE REVIEW

**Comment by koddsson** [comment]
Yes, the description is totally stolen from @JasonEtco 😬

**Comment by j-f1** [comment]
Looks like the app is private.

**Comment by koddsson** [comment]
@j-f1 How so? Is there some config I have to set to public?

**Comment by bkeepers** [comment]
@koddsson On the advanced settings for your GitHub App, there's an option to make the app public.  This is what I currently see when I go to https://github.com/apps/eslint-disable-watcher

about_eslint_disable_watcher

**Comment by koddsson** [comment]
Ahhh! I didn't notice the "Advanced" tab. Maybe the apps should have a banner about it being private or something. Anyways I made it public!

image

**Pull request merged**
