### PR TITLE
Create issuelabeler.md

### PR DESCRIPTION
**Pull request by riyadhalnur**
Add a bot to the list of apps - **Issue Labeler**. The bot tries to automatically assign labels to new issues based on the title and/or body of the issue.

### CODE REVIEW

**Comment by bkeepers** [comment]
Hey @riyadhalnur, thanks for the pull request. The app looks great! 

It looks like there are a few test failures related to this PR:

```
  5) Failure:
lint test::_apps/issuelabeler.md#test_0017_does not use banned words [test/lint_test.rb:50]:
`automatically` should not be used in description

  6) Failure:
lint test::_apps/issuelabeler.md#test_0018_host returns 200 [test/lint_test.rb:58]:
Expected 200 response from https://1th3h69bkc.execute-api.ap-southeast-1.amazonaws.com/production/probot/stats.
Expected: "200"
  Actual: "403"
```

**Comment by bkeepers** [comment]
> For the second one, what do I need to configure in order to let the call through?

I don't actually know what your deployment looks like, but you need to allow `GET /probot/stats` and `GET /ping`.

**Comment by riyadhalnur** [comment]
The tests related to this bot are resolved now 😃 @bkeepers

**Comment by hiimbex** [comment]
Thanks!

**Pull request merged**
