### PR TITLE
Add Repo Assistant AI GitHub App

### PR DESCRIPTION
**Pull request by guillermoscript**
This commit adds the Repo Assistant AI GitHub App, which helps maintainers identify and label duplicate issues automatically. It integrates OpenAI's embeddings and Supabase's database to streamline the workflow by finding similarities between issues, adding labels with a brief description to new issues, sync exiting issues so new issues can be compared and more features are planned for the future.

##### Checklist

- [x] If you're adding a listing for your app, be sure your app is in the `/_apps/` folder before opening this Pull Request.
- [x] All comments in frontmatter need to be removed.
- [x] Performs a useful action through the GitHub API that solves an existing problem for developers: {help maintainers identify and label duplicate issues automatically, add labels to new open issues, sync existing issues. Using the power of OpenAI's embeddings and Supabase's database, more features in the future }
- [x] Is original: for example, it does something not already done by an existing Probot app
- [x] Is using the probot version (v12 or latest)
- [x] [Has tests](https://github.com/guillermoscript/repo-assistant/tree/main/test)
- [x] [Has documentation](https://github.com/guillermoscript/repo-assistant/blob/main/README.md)
- [x] [Is open source](https://github.com/guillermoscript/repo-assistant/)
- [x] [Has a license](https://github.com/guillermoscript/repo-assistant/blob/main/LICENSE)
- [x] [Has a code of conduct](https://github.com/guillermoscript/repo-assistant/blob/main/CODE_OF_CONDUCT.md)
- [x] Has someone willing to at least minimally maintain them for the near future: {guillermoscript}

### CODE REVIEW

**Review by Uzlopak — CHANGES_REQUESTED** [review]
Whats the point of adding a markdown file into _apps folder?

**Comment by guillermoscript** [comment]
Hello @Uzlopak I'm adding my app for review to the website, I'm following the instructions from the [CONTRIBUTING.md](https://github.com/probot/probot.github.io/blob/master/CONTRIBUTING.md) this file says that I need too add a file so that my app can be added, besides that all the other files inside the folders are markdown. So can you be more specific on what do you want me to change ?

**Comment by Uzlopak** [comment]
@guillermoscript 
I apologize, as it could be considered hostile towards your. 
You are right. I was confused because I thought I am in the probot repo. 

;)

**Comment by guillermoscript** [comment]
@Uzlopak its ok, everyone makes mistakes 🤗.

Please if you have any feedback or comments let me know!

**Review by AaronDewes — APPROVED** [review]

**Pull request merged**
