### PR TITLE
Sort by stars high to low

### PR DESCRIPTION
**Pull request by robvanderleek**
Follow-up PR to #377 

I still see the ordering of Apps on the [landing page](https://probot.github.io/) is not by stars. When I run the site locally with `yarn watch` the ordering _is_ based on stars (high to low). This PR puts the `data` prefix in the sort command. If that does not help I do not understand why it works in my development environment but not in production.

### CODE REVIEW

**Comment by gr2m** [comment]
The apps are sorted correctly for me, maybe it's just a caching issue for you?

image

**Comment by robvanderleek** [comment]
Hi @gr2m 😄 

On the Apps page they are, but not on the "Explore" part of the [landing page](https://probot.github.io/) 🤷‍♂️ 
Perhaps this page is statically generated or cached somewhere? (because it is sorted correctly in my development environment)

**Comment by gr2m** [comment]
Oh I see. And have no idea 🤣 @AaronDewes do you know? ☝🏼

**Comment by AaronDewes** [comment]
I wanted to presort this in .eleventy.js, but had a typo, I typed `data.starts` instead of `data.stars`. I'll submit a fix PR soon

**Pull request closed without merging**
