### PR TITLE
chore: Make example on front page ESM

### PR DESCRIPTION
**Pull request by AaronDewes**
This should be merged after v13 is released.

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
nice!

**Comment by AaronDewes** [comment]
@gr2m Can you also grant me access to this repo again?

**Comment by gr2m** [comment]
I thought I did? https://github.com/probot/probot.github.io/invitations

**Comment by AaronDewes** [comment]
Sorry, I forgot to click the link in that email :man_facepalming:

**Pull request merged**
