### PR TITLE
Add Autoapproval app

### PR DESCRIPTION
**Pull request by dkhmelenko**
##### Checklist

- [x] If you're adding a listing for your app, be sure your app is in the `/_apps/` folder before opening this Pull Request.
- [x] All comments in frontmatter need to be removed.
- [x] Performs a useful action through the GitHub API that solves an existing problem for developers: Some of the pull requests created automatically need just to be merged. One of the case - receiving pull requests from localization services, which contain only changes in localization files. In that case, PR should be approved and merged. This app solves the issue with an automatical approval pull request. 
- [x] Is original: for example, it does something not already done by an existing Probot app
- [x] [Has tests](https://github.com/dkhmelenko/autoapproval/tree/master/test)
- [x] [Has documentation](https://github.com/dkhmelenko/autoapproval/blob/master/README.md)
- [x] [Is open source](https://github.com/dkhmelenko/autoapproval)
- [x] [Has a license](https://github.com/dkhmelenko/autoapproval/blob/master/LICENSE)
- [x] [Has a code of conduct](https://github.com/dkhmelenko/autoapproval/blob/master/CODE_OF_CONDUCT.md)
- [x] Has someone willing to at least minimally maintain them for the near future: [dkhmelenko](https://github.com/dkhmelenko)

-----
[View rendered _apps/autoapproval.md](https://github.com/dkhmelenko/probot.github.io/blob/patch-1/_apps/autoapproval.md)

### CODE REVIEW

**Comment by dkhmelenko** [comment]
Would be nice to know what stops from being merged this PR. @bkeepers  @JasonEtco  @hiimbex

**Comment by dkhmelenko** [comment]
This is finally green 🎉

**Review by duongxuantuan154 — APPROVED** [review]
- [ ]

**Review by duongxuantuan154 — COMMENTED** [review]
- [ ]

**Review by duongxuantuan154 — APPROVED** [review]
- [ ]

**Comment by gr2m** [comment]
sorry it took us so long, we've neglected the website for a while, but are trying to catch up now :)

**Comment by dkhmelenko** [comment]
Nice! Thank you!

**Pull request merged**
